### PR TITLE
Correct order of coefficients

### PR DESCRIPTION
**Pull request by McCannDahl**
The "phi" of the example output doesn't look correct. Looking back here https://github.com/tmcclintock/Frisbee_Simulator/blob/b96dedb1a2b7493e20163cfa0d28f98b95e87120/example/example_throw.py it looks like the order of the coefficients may be mixed up.

Comparing the examples from the two repos this fixes the "phi" issue, but the output still looks different from the other repo.

### CODE REVIEW

**Comment by tmcclintock** [comment]
Hey thanks for taking a look at this. A few TODO items before I merge (if you don't have time to take care of them then I will later this week):

- [ ] double check the default coefficients against those provided in Hummel 2003 (where the model was first invented)
- [ ] resolve the values of the moment of inertia tensor (the `I_xx` and `I_zz` variables). It looks like you changed their values in a doc string, but not in the code itself.

**Comment by tmcclintock** [comment]
@McCannDahl thanks again for taking a look at this. I fixed the problem in another PR but I wouldn't have spotted the issue without your careful eye :). Cheers!

**Comment by McCannDahl** [comment]
Thanks man looks great!
Only other issue I found was that sometimes there is a "self.default_initial_conditions" instead of a "self._default_initial_conditions".
I love this repo. Thanks for sharing!

**Comment by tmcclintock** [comment]
You're welcome!

RE _default vs default: I don't think that's an issue. On [this line](https://github.com/tmcclintock/FrisPy/blob/main/frispy/disc.py#L139) `_default_initial_conditions` are used as the "true defaults" (when not arguments are given), and then 11 lines after that the `self.default_initial_conditions` instance variable is set which is the initial conditions set by the user, and it is this variable that is used in the `self.reset_initial_conditions()` method.

Did you have a different pattern in mind?

**Pull request closed without merging**
